security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Provider basé sur l'entité User
        users_in_database:
            entity:
                class: App\Entity\User
                property: email # Utilisez "email" pour identifier l'utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database # Utilise le provider en base de données
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
                username_parameter: email # Utilise l'email comme identifiant
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
        # Exemple d'accès restreint à certaines routes
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/profile, role: ROLE_USER }
